# Makefile

# Linka códigos-objeto (cria executável main)
all: main.o 
	gcc -o program.exe main.c -lm

# Remove executável e códigos-objeto
clean:
	rm -f main *.o

clean_all: 
	rm -f main *.o
	rm -rf *.exe